# Generated by Django 4.2.2 on 2023-06-24 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('critikeye_app', '0005_alter_entreprise_options_alter_entreprise_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technophile',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
