# Generated by Django 4.2.2 on 2023-06-26 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('critikeye_app', '0006_alter_technophile_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entreprise',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='technophile',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
