# Generated by Django 4.2.2 on 2023-06-27 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('critikeye_app', '0007_alter_entreprise_email_alter_technophile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='prenom',
        ),
    ]
